### ISSUE TITLE
About modification of original dist in the re-ranking method

### ISSUE THREAD

**Issue by d-li14** [layumi/Person_reID_baseline_pytorch#104]
Hi @layumi , I noticed that you modified the `original_dist` [here](https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/re_ranking.py#L47) instead of the original squared norm. Could you explain how we can understand this? Thanks.

**Comment by dyh127** [comment]
the former one is cos distance(np.power(original_dist, 2).astype(np.float32)), the new one is Euclidean distance(2. - 2 * original_dist)
explain:
first, original_dist is an cos distance matrix, it's a (M+N)*(M+N) matrix, and M is length of query, N is length of gallery, and every element (i, j) of the matrix is cos distance of feature_i and feature_j.
second, the former one, np.power(original_dist, 2).astype(np.float32) means power to each elements which also results a cos distance
final, the new one, (2. - 2 * original_dist) means (feature_i)^2 + (feature_j)^2 - 2*(feature_i)*(feature_j) for every element in the matrix, because feature is normalized, so （feature_i）^2 = 1

**Comment by d-li14** [comment]
@dyh127 Thanks, but how did you get "feature is normalized"?

**Comment by layumi** [comment]
Thank you @dyh127 

Hi @d-li14 , 
You are right. I made a mistake that I forgot to add the square function. 
Although this mistake did not lead to a worse result, it is optional (Since we still keep the similarity order).
 
The right version should be 
```python
original_dist = 2. - 2 * original_dist   # change the cosine similarity metric to euclidean similarity metric
original_dist = np.power(original_dist, 2).astype(np.float32)
```

I will test the result and then modify the code later. 
Thank you very much! @d-li14

**Comment by rickllyxu** [comment]
> Thank you @dyh127
> 
> Hi @d-li14 ,
> You are right. I made a mistake that I forgot to add the square function.
> Although this mistake did not lead to a worse result, it is optional (Since we still keep the similarity order).
> 
> The right version should be
> 
> ```python
> original_dist = 2. - 2 * original_dist   # change the cosine similarity metric to euclidean similarity metric
> original_dist = np.power(original_dist, 2).astype(np.float32)
> ```
> 
> I will test the result and then modify the code later.
> Thank you very much! @d-li14

hi, sorry to catch your thoughts.
I still can not understand the meaning of the code `original_dist = np.power(original_dist, 2).astype(np.float32)`.
The initial `original_dist ` is cosine distance, right? Before calculate this cosine distance, the feature of each item should have been normalized (for example, new_feat(i) = feat(i) / ||feat(i)||_2 ).
Then ` 2. - 2 * original_dist` is equivalent to `new_feat(i)^2 + new_feat(j)^2 - 2 * new_feat(i) * new_feat(j)^T`, same as @dyh127 said, which converts the cos dist to euclidean dist.
So I cannot understand why we need to apply square function.
Is there any misunderstand? Thanks

**Comment by rickllyxu** [comment]
> > Thank you @dyh127
> > Hi @d-li14 ,
> > You are right. I made a mistake that I forgot to add the square function.
> > Although this mistake did not lead to a worse result, it is optional (Since we still keep the similarity order).
> > The right version should be
> > ```python
> > original_dist = 2. - 2 * original_dist   # change the cosine similarity metric to euclidean similarity metric
> > original_dist = np.power(original_dist, 2).astype(np.float32)
> > ```
> > 
> > 
> > I will test the result and then modify the code later.
> > Thank you very much! @d-li14
> 
> hi, sorry to catch your thoughts.
> I still can not understand the meaning of the code `original_dist = np.power(original_dist, 2).astype(np.float32)`.
> The initial `original_dist ` is cosine distance, right? Before calculate this cosine distance, the feature of each item should have been normalized (for example, new_feat(i) = feat(i) / ||feat(i)||_2 ).
> Then ` 2. - 2 * original_dist` is equivalent to `new_feat(i)^2 + new_feat(j)^2 - 2 * new_feat(i) * new_feat(j)^T`, same as @dyh127 said, which converts the cos dist to euclidean dist.
> So I cannot understand why we need to apply square function.
> Is there any misunderstand? Thanks

OK, I find answer in #140
