### ISSUE TITLE
Do you use cuhk03 evaluation metric or market1501 evaluation metric?

### ISSUE THREAD

**Issue by Wanggcong** [layumi/Person_reID_baseline_pytorch#13]

**Comment by layumi** [comment]
The evaluation metric is wrote for Market1501, DukeMTMC-reID and CUHK03-NP.
It is not proper for CUHK03. It needs training 20 models (based on different training set) and testing 20 models (different testing set). It reports the average rank-1, rank-5 and rank-10 score. 
If you want to run CUHK03, you may refer to the caffe evaluation code (You may google it).

**Comment by Wanggcong** [comment]
Maybe I do not clarify the point. The cuhk03 and market evaluation metric I mentioned above are two different methods that compute the cmc curve.  See the url: https://cysu.github.io/open-reid/notes/evaluation_metrics.html.

I wonder which metric you use in these experiments. ( I guess it is the market evaluation metric.)

**Comment by layumi** [comment]
Hi @Wanggcong ,
Since the code runs on Market1501, we use the evaluation metric based on Market1501.
I converted the original code(Matlab version) to python version. 
I checked the result. It is the same when running on the original Matlab code.

The evaluation code in Open re-id may be slightly different from me.

**Comment by Wanggcong** [comment]
Thanks for your help! @layumi
