### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

### ISSUE THREAD

**Issue by Rachel3210** [layumi/Person_reID_baseline_pytorch#15]
Have you met this problem.when I am running train.py
![1](https://user-images.githubusercontent.com/37760157/37871149-641e296c-3019-11e8-8d5c-abe9c8764178.PNG)
after about ten minutes.....
![17](https://user-images.githubusercontent.com/37760157/37871154-af81b874-3019-11e8-94d9-26555846cd31.PNG)
Do you have any idea about this?
Thanks a lot.

**Comment by layumi** [comment]
Hi @Rachel3210 
It seems to be the network problem.
Would you like to download the `pth` file ? Then put it to the `/home/your-name/.torch/models/`.

**Comment by Rachel3210** [comment]
I can use conda to install pytorch, maybe not the problem with the network.
And I also tried to download the pth file, but I failed to name the file with .torch on my server.
would it  be the problem with the proxy or firewall of my server? just like the blog said
[https://stackoverflow.com/questions/16775534/python-and-proxy-urllib2-urlerror-urlopen-error-errno-110-connection-timed](url)

**Comment by layumi** [comment]
@Rachel3210 
`.torch` is a dir name.
You may use `mkdir .torch` to create a dir first.

**Comment by Rachel3210** [comment]
OK, I will have a try. Thank you for giving me suggestions.

**Comment by Mr-zhu0912** [comment]
emmm.I also meet this problem.so,Do you solve this maybe a network problem?If you get it,can tell me the way to make it ok.

**Comment by Mr-zhu0912** [comment]
and in my computer i have the dir named .torch/models.

**Comment by Rachel3210** [comment]
have you tried to download the pth file ? Then put it to the /home/your-name/.torch/models/? @Mr-zhu0912

**Comment by Mr-zhu0912** [comment]
yes ,i try do it.but the link of the pth file break off all the time.so,you can provide a share link about pth file ,like baiduyun,or sent to my email.thank you. @Rachel3210

**Comment by Rachel3210** [comment]
give me your email @Mr-zhu0912

**Comment by Mr-zhu0912** [comment]
2941746806@qq.com   ok,thanks very much!

**Comment by Mr-zhu0912** [comment]
thanks.I receive it.and i try it again immediately

**Comment by Mr-zhu0912** [comment]
I run model.py again.But it occur this problem.
![2018-03-26 21-07-49](https://user-images.githubusercontent.com/35393647/37908253-3d258856-313a-11e8-8346-ed027fe511b9.png)
so,i begin to find problem,i alter (pretrained=True) to (pretrained=False),
![2018-03-26 21-08-58](https://user-images.githubusercontent.com/35393647/37908360-97e5893a-313a-11e8-8c92-278bc7310e56.png)
end,it worked,and output this.
![2018-03-26 21-09-16](https://user-images.githubusercontent.com/35393647/37908400-b131f27a-313a-11e8-840b-f6b78bc8a2a8.png)
But,i can't know the result is true or false?
so.please tell me about it.thank you a lot.

**Comment by layumi** [comment]
Hi @Mr-zhu0912 
If `pertrained=Ture`, the pre-trained model will be used to initialize the network.
In our case, we need the ImageNet pre-trained model. (You just downloaded.)

Have you downloaded the both model DenseNet121 and ResNet50?

**Comment by Rachel3210** [comment]
I solved the problem with your suggestion. Thanks a lot. @layumi

**Comment by Mr-zhu0912** [comment]
@layumi yes,i download the DenseNet121 and ResNet50 from github and put them in Person_reID_baseline_pytorch-master/model because i can't  register the gooledrive in you github.
![2018-03-28 11-00-39](https://user-images.githubusercontent.com/35393647/38006558-1841864a-3278-11e8-99aa-d8c2b2dd9569.png)
![2018-03-28 11-00-57](https://user-images.githubusercontent.com/35393647/38006562-1e343f34-3278-11e8-8b8a-d0427ecccb1d.png)
so,what can i do for this problem?thanks.

**Comment by layumi** [comment]
Hi @Mr-zhu0912, 
First, we use the official model from pytorch website rather than github. The github code that you found is not necessary.

In fact, my code can automatically download the pretrained models. But the Great Wall may block the pytorch. So you may need to download the model by hand and put them into the path  `/home/your-name/.torch/models/`.
