### ISSUE TITLE
How to train vs test

### ISSUE THREAD

**Issue by hello1910** [layumi/Person_reID_baseline_pytorch#45]
Thanks so much for providing such an excellent codebase.

I'm sorry if this is too simple a question.  The model is trained as a classification problem (input were images and output was ID numbers). If the model was previously outputting ID numbers during training, how would it output retrieved images during testing?

**Comment by layumi** [comment]
Hi @hello1910 

Did you mean regressing the ID number (regression task) instead of the solution in this repo (classification task)? 

In fact, classification and regression task is similar.
But classification is more easy to train. We learn the probability [0,1] that the image are classified as A.  For the regression task, we need to regress the integer {0,1,2...751} .
