### ISSUE TITLE
How can I understand this line of re_ranking.py?

### ISSUE THREAD

**Issue by ghost** [layumi/Person_reID_baseline_pytorch#68]
`jaccard_dist[i] = [1-temp_min/(2.-temp_min)`](https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/re_ranking.py#L92)
why 2 - temp_min  equal to temp_max as the paper said?

I know that the previous code is  used to calculate the soft values of the corresponding position of the probe vector and some gallery vectors. But I can not understand the meaning of 2 - temp_min. it is so confused. I calculate the temp_max by replace np.minimum with np.maximum .But temp_max + temp_min != 2.

thanks for your explanation

**Comment by DengpanFu** [comment]
The explanation can be found at paper [Sparse Contextual Activation for Efficient Visual Re-ranking, TIP, 2016](https://www.researchgate.net/publication/289496002_Sparse_Contextual_Activation_for_Efficient_Visual_Re-Ranking) section III.C. But i think the implementation may have a little problem, because Local Query Expansion was done first( https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/re_ranking.py#L72-L77), which may destroy the property of L1-Norm=1, that's why temp_max + temp_min !=2 @jj8401 , I don't know how this will affect the final result. Can @layumi @zhunzhong07  give some explanations? Thanks.

**Comment by d-li14** [comment]
@zhunzhong07 Any Update? I'm also kind of confused about that.

**Comment by magicffourier** [comment]
@zhunzhong07 I'm also kind of confused about this line. Can you explain about it?

**Comment by zhunzhong07** [comment]
Sorry for the late reply. @d-li14 @magicffourier @jj8401

1) |Vi|_1 = 1,  |Vj|_1 = 1 (Because they are L1 normlized)
2) |Vi|_1 + |Vj|_1 = |Min(Vi, Vj)|_1 + |Max(Vi, Vj)|_1 =  2
3) Thus, |Max(Vi, Vj)|_1 =  2 - |Min(Vi, Vj)|_1
4) For |Min(Vi, Vj)|_1, we could directly calculate |Min(Vi, Vj)|_1 with the min weights of neighors that only belong to Vi.
5) However, for |Max(Vi, Vj)|_1, directly replace np.minimum with np.maximum in line-92 would not get |Max(Vi, Vj)|_1. Because we should also consider the weights (>0) of neighbors that belong to Vj. Thus, we use |Max(Vi, Vj)|_1 =  2 - |Min(Vi, Vj)|_1 to facilitate the calculation of |Max(Vi, Vj)|_1.
